### ISSUE TITLE
能否将编辑器和view打包的npm包

### ISSUE THREAD

**Issue by sangeren** [meterXu/xsLab#36]
你好：
能否将编辑器和view打包的npm包，然后以npm包的方式引入？
谢谢

**Comment by sangeren** [comment]
我创建了一个项目，将编译好xslab-editor放到node_modules目录下面，的然后引用mteditor.vue出现了很多问题，比如：样式，vue的原型链扩展方法都报错，this.$Modal也报错。
有没有更好的引入方式，或者是我处理的不对？

**Comment by meterXu** [comment]
1、这个项目用的是ivew组件，如果你的项目使用其他UI，可能导致不兼容
2、直接使用编译好的xslab-editor，放在项目的node_modules下，可能导致某些资源找不到，请先确定一下打包时设置的资源路径
3、本项目使用的时vue2版本，如果你使用vue3进行集成，可能会有兼容性

**Comment by sangeren** [comment]
![image](https://github.com/meterXu/xsLab/assets/8380824/0b9174fa-27fa-4464-88a8-8461e0a816e7)

现在主要是这个问题了，是不是写法的问题？
